import uuid
from typing import Any

from sqlalchemy import BigInteger, Identity, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampMixin


class Agent(Base, TimestampMixin):
    """A single agents table.

    Type-specific data (messages, instructions, input/output variables, ...)
    lives in the ``agent_metadata`` JSONB column, keyed by ``agent_type``.
    Validation of that payload happens in the Pydantic layer before it is
    persisted here.
    """

    __tablename__ = "agents"

    # DB-managed auto-incrementing numeric id (equivalent to BIGSERIAL).
    seq_id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(),
        unique=True,
        nullable=False,
    )
    # UUID primary key, generated by the app.
    agent_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    agent_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    agent_metadata: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
