import uuid
from typing import Any

from sqlalchemy import BigInteger, Identity, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampMixin


class Workflow(Base, TimestampMixin):
    """A workflow: a directed graph of agent-executing nodes.

    The full graph (start node, nodes, edges, conditions, calling config) is
    stored in the ``definition`` JSONB column. Structural validation and
    agent-reference integrity are enforced in the app layer before persisting.
    """

    __tablename__ = "workflows"

    # DB-managed auto-incrementing numeric id (equivalent to BIGSERIAL).
    seq_id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(),
        unique=True,
        nullable=False,
    )
    # UUID primary key, generated by the app (not the workflow_id inside the JSON).
    workflow_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    definition: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
